version: 1.0.{build}
image: Visual Studio 2017
build: off
test_script:
- ps: ./cake.ps1 -target=pack

artifacts:
  - path: '3-dist\**.symbols.nupkg'
  
deploy:
  provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: "0qN7BoUb0LplVajjpnT8cm2ZQu+mpCuVv1cPrPjb/ornampptpQ1JmKtCvrF27zr"
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
