version: 2

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - checkout
      - run: ./cake.sh -target=test
      
workflows:
  version: 2
  test:
    jobs:
      - test
