name: test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: dotnet --info
      run: dotnet --info
    - name: test
      shell: pwsh
      run: ./cake.ps1 -target=pack
