name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      # https://hub.docker.com/_/microsoft-dotnet-core-sdk/
      image: mcr.microsoft.com/dotnet/core/sdk:3.0-alpine
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: test
        shell: sh
        run: ./cake.sh -target=pack
